ALTER USER 'root'@'localhost' IDENTIFIED BY 'ROOT_MYSQL_PASS';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');

DROP DATABASE IF EXISTS DB_NAME;
DELETE FROM mysql.db WHERE Db='DB_NAME' OR Db='DB_NAME\\_%';
CREATE DATABASE DB_NAME;

DELETE FROM mysql.user WHERE User='APP_DB_USER';
DROP USER IF EXISTS 'APP_DB_USER';
CREATE USER 'APP_DB_USER'@'%' IDENTIFIED BY 'APP_DB_PASS';
GRANT ALL PRIVILEGES ON DB_NAME.*  TO 'APP_DB_USER'@'%';
FLUSH PRIVILEGES;
