name: Terraform VPC Deploy

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'terraform/vpc/**'

jobs:
  tf-vpc-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SEC: ${{ secrets.AWS_SEC }}
      TF_EXT: ${{ secrets.TF_EXT }}
    container: docker://niceandgoodonline/tf-awscli:latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy fr-4640-term VPC
      run: |
        source .github/sh/aws_auth.sh
        source .github/sh/assume_tf_iamrole.sh
        source .github/sh/vars.sh
        cd terraform/vpc
        terraform init
        terraform apply -auto-approve
